=== Yash-H-Kataria/Webstack/Grocery Store/xml/GroceryStoreSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="GroceryStore">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element name="Product" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="ProductName" type="xsd:string"/>
            <xsd:element name="Category" type="xsd:string"/>
            <xsd:element name="ExpiryDate">
              <xsd:simpleType>
                <xsd:restriction base="xsd:date">
                  <xsd:minInclusive value="2020-01-01"/>  <!-- YYYY-MM-DD Format  -->
                  <xsd:maxInclusive value="2020-12-31"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:element>
            <xsd:element name="Price" type="xsd:decimal"/>
            <xsd:element name="Quantity">
              <xsd:simpleType>
                <xsd:restriction base="xsd:integer">
                  <xsd:minExclusive value="0"/> 
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="Employee" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="EmployeeName" type="xsd:string"/>
            <xsd:element name="Salary" type="xsd:integer"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
</xsd:schema>

=== Yash-H-Kataria/Webstack/Grocery Store/xml/GroceryStore.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="GroceryStoreStyling.xsl"?>
<GroceryStore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="GroceryStoreSchema.xsd">
    
    <!--  Products  -->
    <Product>
        <ProductName>Oreo Biscuit</ProductName>
        <Category>Biscuit</Category>
        <ExpiryDate>2020-09-17</ExpiryDate>
        <Price>20</Price>
        <Quantity>300</Quantity>
    </Product>
    <Product>
        <ProductName>Parle G</ProductName>
        <Category>Biscuit</Category>
        <ExpiryDate>2020-05-15</ExpiryDate>
        <Price>10</Price>
        <Quantity>320</Quantity>
    </Product>
    <Product>
        <ProductName>Lays Cream n Onion</ProductName>
        <Category>Waffer</Category>
        <ExpiryDate>2020-02-10</ExpiryDate>
        <Price>15</Price>
        <Quantity>550</Quantity>
    </Product>
    <Product>
        <ProductName>Hide &amp; Seek Choco Chips </ProductName>
        <Category>Biscuit</Category>
        <ExpiryDate>2020-07-25</ExpiryDate>
        <Price>50</Price>
        <Quantity>140</Quantity>
    </Product>
    <Product>
        <ProductName>Uncle Chips</ProductName>
        <Category>Waffer</Category>
        <ExpiryDate>2020-05-02</ExpiryDate>
        <Price>15</Price>
        <Quantity>450</Quantity>
    </Product>
    <Product>
        <ProductName>Good Day</ProductName>
        <Category>Biscuit</Category>
        <ExpiryDate>2020-11-19</ExpiryDate>
        <Price>30</Price>
        <Quantity>390</Quantity>
    </Product>
    <Product>
        <ProductName>Balaji Tomato Masti</ProductName>
        <Category>Waffer</Category>
        <ExpiryDate>2020-07-07</ExpiryDate>
        <Price>10</Price>
        <Quantity>280</Quantity>
    </Product>

    <!-- Employees -->
    <Employee>
        <EmployeeName>Yash Kataria</EmployeeName>
        <Salary>20000</Salary>
    </Employee>
    <Employee>
        <EmployeeName>Praneet Kaisare</EmployeeName>
        <Salary>25000</Salary>
    </Employee>
    <Employee>
        <EmployeeName>Kishan Mistry</EmployeeName>
        <Salary>18000</Salary>
    </Employee>
    <Employee>
        <EmployeeName>Pulkit Bhagwate</EmployeeName>
        <Salary>15000</Salary>
    </Employee>
    <Employee>
        <EmployeeName>Souvik Datta</EmployeeName>
        <Salary>20000</Salary>
    </Employee>
    <Employee>
        <EmployeeName>Joswin D'souza</EmployeeName>
        <Salary>23000</Salary>
    </Employee>

</GroceryStore>
