=== Yash-H-Kataria/Webstack/CIA1 Test/EMSSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<!-- 

Name :- Yash H. Kataria
Reg No :- 2047235

 -->

<xsd:element name="Company">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element name="Employee" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="EmpName" type="xsd:string"/>
            
            <xsd:element name="EmpAge" type="xsd:integer"/>
            
            <xsd:element name="EmpSalary">
              <xsd:simpleType>
                <xsd:restriction base="xsd:integer">
                  <xsd:minInclusive value="50000"/> 
                  <xsd:maxInclusive value="200000"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:element>
            
            <xsd:element name="EmpEmailId" type="xsd:string"/>
            
            <xsd:element name="EmpPhoneNumber" type="xsd:integer"/>
            
            <xsd:element name="EmpDesignation" type="xsd:string"/>
          </xsd:sequence>

          <xsd:attribute name="EmpID">
            <xsd:simpleType>
              <xsd:restriction base="xsd:integer">
                  <xsd:minInclusive value="1"/>
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>

        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
</xsd:schema>

=== Yash-H-Kataria/Webstack/CIA1 Test/EMS.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="EMSStyling.xsl"?>

<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="EMSSchema.xsd">

      <!-- 

        Name :- Yash H. Kataria
        Reg No :- 2047235

        -->

      <!-- List of Employee Details -->
    
    <Employee EmpID="1">
        <EmpName>Yash Kataria</EmpName>
        <EmpAge>50</EmpAge>
        <EmpSalary>90000</EmpSalary>
        <EmpEmailId>katariayash007@gmail.com</EmpEmailId>
        <EmpPhoneNumber>9512136600</EmpPhoneNumber>
        <EmpDesignation>CEO</EmpDesignation>
    </Employee>

    <Employee EmpID="2">
        <EmpName>Praneet Kaisare</EmpName>
        <EmpAge>45</EmpAge>
        <EmpSalary>80000</EmpSalary>
        <EmpEmailId>kaisarepraneet@gmail.com</EmpEmailId>
        <EmpPhoneNumber>9898100471</EmpPhoneNumber>
        <EmpDesignation>CFO</EmpDesignation>
    </Employee>

    <Employee EmpID="3">
        <EmpName>Kishan Mistry</EmpName>
        <EmpAge>25</EmpAge>
        <EmpSalary>75000</EmpSalary>
        <EmpEmailId>kishanmistry@gmail.com</EmpEmailId>
        <EmpPhoneNumber>8469126853</EmpPhoneNumber>
        <EmpDesignation>Project Head</EmpDesignation>
    </Employee>

    <Employee EmpID="4">
        <EmpName>Pulkit Bhagwate</EmpName>
        <EmpAge>48</EmpAge>
        <EmpSalary>100000</EmpSalary>
        <EmpEmailId>bhagwatepulkit@gmail.com</EmpEmailId>
        <EmpPhoneNumber>9852136600</EmpPhoneNumber>
        <EmpDesignation>HR</EmpDesignation>
    </Employee>

    <Employee EmpID="5">
        <EmpName>Souvik Datta</EmpName>
        <EmpAge>25</EmpAge>
        <EmpSalary>88000</EmpSalary>
        <EmpEmailId>souvikdatta@gmail.com</EmpEmailId>
        <EmpPhoneNumber>9532347755</EmpPhoneNumber>
        <EmpDesignation>Manager</EmpDesignation>
    </Employee>

    <Employee EmpID="6">
        <EmpName>Joswin D'souza</EmpName>
        <EmpAge>46</EmpAge>
        <EmpSalary>120000</EmpSalary>
        <EmpEmailId>joswin@gmail.com</EmpEmailId>
        <EmpPhoneNumber>9898136600</EmpPhoneNumber>
        <EmpDesignation>Project Head</EmpDesignation>
    </Employee>
</Company>
